# A config for dot files to be managed by a dotfile manager called dotdrop.
config:
  backup: true
  banner: true
  create: true
  dotpath: .
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

actions:
  pre:
    catppuccin_delta: which delta && wget https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig -O "{{@@ env['XDG_CONFIG_HOME'] @@}}/git/catppuccin.gitconfig"
    catppuccin_bat: which bat && mkdir -p $(bat --config-dir)/themes && wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme && bat cache --build
    fzf: test -e "{{@@ env['XDG_CONFIG_HOME'] @@}}/fzf" || (git clone --depth 1 https://github.com/junegunn/fzf.git {{@@ env['XDG_CONFIG_HOME'] @@}}/fzf; {{@@ env['XDG_CONFIG_HOME'] @@}}/fzf/install)
    vim-plug-install: test -e "{{@@ env['XDG_CONFIG_HOME'] @@}}/vim/autoload/plug.vim" || (mkdir -p "{{@@ env['XDG_CONFIG_HOME'] @@}}/vim/autoload"; curl
      -fLo "{{@@ env['XDG_CONFIG_HOME'] @@}}/vim/autoload/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    vim-plug: vim +PlugInstall +qall
  tmux_tpm: git clone https://github.com/tmux-plugins/tpm "{{@@env ['XDG_DATA_HOME'] @@}}/tpm"


variables:
    link_value: "nolink"

dotfiles:
  nvim:
    src: nvim
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/nvim"
    link: "{{@@ link_value @@}}"

  vim:
    src: vim
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/vim"
    link: "{{@@ link_value @@}}"
    actions:
       - fzf
       - vim-plug-install
       - vim-plug

  grm:
    src: grm
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/grm"
    link: "{{@@ link_value @@}}"

  fish:
    src: fish
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/fish"
    link: "{{@@ link_value @@}}"
  git:
    src: git
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/git"
    link: "{{@@ link_value @@}}"
  tmux_conf:
    src: tmux
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/tmux"
    link: "{{@@ link_value @@}}"
    actions:
      - tmux_tpm
  wezterm_conf_unix:
    src: wezterm
    dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/wezterm"
    link: "{{@@ link_value @@}}"
  wezterm_conf_wsl:
    src: wezterm
    dst: "/mnt/c/Users/Erik\ Lilja"
    chmod: preserve
    link: "nolink"

profiles:
  nix:
    dotfiles:
    - vim
    - nvim
    - wezterm_conf_unix
    - fish
    - git
    - grm
    - tmux_conf
    variables:
      link_value: "link"
    actions:
      - catppuccin_bat
      - catppuccin_delta


  wsl:
    dotfiles:
    - wezterm_conf_wsl

