#!/bin/bash
#################################
# General
#################################
alias ..="change_dir_and_ls .."
alias ....="change_dir_and_ls ../.."
alias ......="change_dir_and_ls ../../.."

# Colors please
[ "$(uname)" = "Linux" ] && alias ls="ls --color=auto"
[ "$(uname)" = "Darwin" ] && alias ls="ls -G"

function change_dir_and_ls_pushd {
    pushd $1 && ls
}
function change_dir_and_ls {
    cd $1 && ls
}

unalias cd >/dev/null 2>&1
alias cd="change_dir_and_ls"
alias grep="grep --color=auto"

alias ll="ls -alF"
alias l="ls -alF"

# Remove what popd returns. Not interesting.
alias popd="popd > /dev/null"

# Remove what pushd returns. Not interesting.
alias pushd="pushd >/dev/null"

# Set dirs = dirs -v
# Also remove first line as it does not give anything(to me).
alias dirs="dirs -v | tail -n +2"

# Wanna watch some star wars?
alias starwars="telnet towel.blinkenlights.nl"

# Do you have a bunch of lines with integers that you want to sum?
alias sumlines="awk '{s+=\$1} END {print s}'"

#################################
# Docker
################################
function __dps { docker ps $1 }
function __dex { docker exec -it $1 $2 }
alias dps='__dps'
alias dex='__dex'

#################################
# Git
#################################
alias fwl='--force-with-lease'

#################################
# Dumb settings
#################################
EDITOR="vim"
alias vmi=$EDITOR
alias viom=$EDITOR

alias gti="git"
alias ls-l="ls -l"

# Shortcuts
alias cddev="change_dir_and_ls_pushd ~/code"
alias dots="change_dir_and_ls_pushd ~/dotfiles"

