#!/bin/bash
# Colors please
alias ls="ls --color=auto"

function change_dir_and_ls_pushd {
    pushd $1 && ls
}
function change_dir_and_ls {
    cd $1 && ls
}

alias cd="change_dir_and_ls"
alias grep="grep --color=auto"

alias ll="ls -alF"

# Remove what popd returns. Not interesting.
alias popd="popd > /dev/null"

# Remove what pushd returns. Not interesting.
alias pushd="pushd >/dev/null"

# Set dirs = dirs -v
# Also remove first line as it does not give anything(to me).
alias dirs="dirs -v | tail -n +2"

#################################
# Docker
################################
function __dps { docker ps $1 }
function __dex { docker exec -it $1 $2 }
alias dps='__dps'
alias dex='__dex'

#################################
# Dumb settings
#################################
EDITOR="vim"
alias vmi=$EDITOR
alias viom=$EDITOR

alias gti="git"
alias ls-l="ls -l"

# Shortcuts
alias cddev="change_dir_and_ls_pushd ~/code"
alias dots="change_dir_and_ls_pushd ~/dotfiles"
